#! /bin/bash

printf "Running pre-commit hooks\n"

printf "Generating docs.json..."

if elm make --docs=docs.json > /dev/null 2>&1; then
    printf "Success!"
else 
    printf "Failed!"
    exit 1
fi

printf "Running elm-format..."

if elm-format . --yes > /dev/null 2>&1; then
    printf "Success!"
else 
    printf "Failed!"
    exit 1
fi

printf "Staging changed files"

git add .

printf "Pre-commit hooks complete\n"

exit 0