module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
-}

import Array
import Dict
import Expect
import Fuzz
import Gadget
import Gadget.Adapter.Diff
import Gadget.Adapter.Fuzz
import Gadget.Adapter.Html
import Gadget.Adapter.Json
import Gadget.Adapter.Random
import Gadget.Adapter.String
import Html
import Json.Decode
import Json.Encode
import Parser
import Random
import Set
import Test


tests : Test.Test
tests =
    Test.describe
        "documentation code snippets"
        [ Test.describe
            "readme"
            [ Test.describe
                "code snippet 0"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Json.Decode.Value
                            unused =
                                json__Readme_0
                        in
                        Expect.pass
                    )
                , Test.test
                    "1"
                    (\() ->
                        decoded__Readme_0
                            |> Expect.equal (Result.Ok input__Readme_0)
                    )
                , Test.test
                    "2"
                    (\() ->
                        fuzzed__Readme_0
                            |> Expect.equal [ { age = 92, name = "o \n\\" } ]
                    )
                ]
            ]
        , Test.describe
            "Gadget"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget Person__Gadget__Header_0
                                unused =
                                    personGadget__Gadget__Header_0
                            in
                            Expect.pass
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget Shape__Gadget__Header_1
                                unused =
                                    shapeGadget__Gadget__Header_1
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "array"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Array.Array Basics.Int)
                                unused =
                                    arrayGadget__Gadget__array_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "dict"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Dict.Dict Basics.Int String.String)
                                unused =
                                    dictGadget__Gadget__dict_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "label"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget Basics.Int
                                unused =
                                    labelled__Gadget__label_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "list"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (List Basics.Int)
                                unused =
                                    listGadget__Gadget__list_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "map"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (List Char.Char)
                                unused =
                                    charListGadget__Gadget__map_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "maybe"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Maybe.Maybe Basics.Int)
                                unused =
                                    maybeGadget__Gadget__maybe_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "result"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Result.Result String.String Basics.Int)
                                unused =
                                    resultGadget__Gadget__result_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "set"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Set.Set Basics.Int)
                                unused =
                                    dictGadget__Gadget__set_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "triple"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget ( String.String, Basics.Int, Basics.Float )
                                unused =
                                    tripleGadget__Gadget__triple_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "tuple"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget ( String.String, Basics.Int )
                                unused =
                                    tupleGadget__Gadget__tuple_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Diff"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Adapter.Diff.Changes
                                unused =
                                    changes__Gadget_Adapter_Diff__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Gadget.Adapter.Diff.patch
                                gadget__Gadget_Adapter_Diff__Header_0
                                changes__Gadget_Adapter_Diff__Header_0
                                oldValue__Gadget_Adapter_Diff__Header_0
                                |> Expect.equal (Result.Ok [ 1, 2, 3, 4 ])
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Fuzz"
            [ Test.describe
                "fuzzer"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            fuzzedPerson__Gadget_Adapter_Fuzz__fuzzer_0
                                |> Expect.equal
                                    [ { age = 92, name = "o \n\\" } ]
                        )
                    ]
                ]
            , Test.describe
                "fuzzerWithOverrides"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            fuzzedPerson__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0
                                |> Expect.equal [ { age = 105, name = "Ed" } ]
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Html"
            [ Test.describe
                "view"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Html.Html msg
                                unused =
                                    view__Gadget_Adapter_Html__view_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Json"
            [ Test.describe
                "decoder"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            result__Gadget_Adapter_Json__decoder_0
                                |> Expect.equal (Result.Ok 1)
                        )
                    ]
                ]
            , Test.describe
                "encode"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Json.Encode.Value
                                unused =
                                    json__Gadget_Adapter_Json__encode_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            jsonString__Gadget_Adapter_Json__encode_0
                                |> Expect.equal "{\"int\":1}"
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Random"
            [ Test.describe
                "generator"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            randomPerson__Gadget_Adapter_Random__generator_0
                                |> Expect.equal { age = -1353461051, name = "" }
                        )
                    ]
                ]
            , Test.describe
                "generatorWithOverrides"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            randomPerson__Gadget_Adapter_Random__generatorWithOverrides_0
                                |> Expect.equal { age = -97690584, name = "Ed" }
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.String"
            [ Test.describe
                "parser"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            parsed__Gadget_Adapter_String__parser_0
                                |> Expect.equal (Result.Ok [ 1, 2, 3 ])
                        )
                    ]
                ]
            , Test.describe
                "print"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            printed__Gadget_Adapter_String__print_0
                                |> Expect.equal "l[i(1),i(2),i(3)]"
                        )
                    ]
                ]
            ]
        ]


type alias User__Readme_0 =
    { name : String.String, age : Basics.Int }


input__Readme_0 =
    { name = "Ed", age = 44 }


gadget__Readme_0 : Gadget.Gadget User__Readme_0
gadget__Readme_0 =
    Gadget.record User__Readme_0
        |> Gadget.field .name Gadget.string
        |> Gadget.field .age Gadget.int
        |> Gadget.endRecord


json__Readme_0 =
    Gadget.Adapter.Json.encode gadget__Readme_0 input__Readme_0


decoded__Readme_0 =
    Json.Decode.decodeValue
        (Gadget.Adapter.Json.decoder gadget__Readme_0)
        json__Readme_0


fuzzed__Readme_0 =
    Fuzz.examples 1 (Gadget.Adapter.Fuzz.fuzzer gadget__Readme_0)


type alias Person__Gadget__Header_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget__Header_0 =
    Gadget.record Person__Gadget__Header_0
        |> Gadget.field .name Gadget.string
        |> Gadget.field .age Gadget.int
        |> Gadget.endRecord


type Shape__Gadget__Header_1
    = Rectangle__Gadget__Header_1 Basics.Int Basics.Int
    | Circle__Gadget__Header_1 Basics.Int


shapeGadget__Gadget__Header_1 =
    Gadget.custom
        (\rectangle circle variant ->
            case variant of
                Rectangle__Gadget__Header_1 width height ->
                    rectangle width height

                Circle__Gadget__Header_1 radius ->
                    circle radius
        )
        |> Gadget.variant2 Rectangle__Gadget__Header_1 Gadget.int Gadget.int
        |> Gadget.variant1 Circle__Gadget__Header_1 Gadget.int
        |> Gadget.endCustom


arrayGadget__Gadget__array_0 =
    Gadget.array Gadget.int


dictGadget__Gadget__dict_0 =
    Gadget.dict Gadget.int Gadget.string


labelled__Gadget__label_0 =
    Gadget.int |> Gadget.label "age"


listGadget__Gadget__list_0 =
    Gadget.list Gadget.int


charListGadget__Gadget__map_0 =
    Gadget.string |> Gadget.map String.toList String.fromList


maybeGadget__Gadget__maybe_0 =
    Gadget.maybe Gadget.int


resultGadget__Gadget__result_0 =
    Gadget.result Gadget.string Gadget.int


dictGadget__Gadget__set_0 =
    Gadget.set Gadget.int


tripleGadget__Gadget__triple_0 =
    Gadget.triple Gadget.string Gadget.int Gadget.float


tupleGadget__Gadget__tuple_0 =
    Gadget.tuple Gadget.string Gadget.int


gadget__Gadget_Adapter_Diff__Header_0 =
    Gadget.list Gadget.int


oldValue__Gadget_Adapter_Diff__Header_0 =
    [ 1, 2, 3 ]


newValue__Gadget_Adapter_Diff__Header_0 =
    [ 1, 2, 3, 4 ]


changes__Gadget_Adapter_Diff__Header_0 =
    Gadget.Adapter.Diff.diff
        gadget__Gadget_Adapter_Diff__Header_0
        oldValue__Gadget_Adapter_Diff__Header_0
        newValue__Gadget_Adapter_Diff__Header_0


type alias Person__Gadget_Adapter_Fuzz__fuzzer_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget_Adapter_Fuzz__fuzzer_0 =
    Gadget.record Person__Gadget_Adapter_Fuzz__fuzzer_0
        |> Gadget.field .name Gadget.string
        |> Gadget.field .age Gadget.int
        |> Gadget.endRecord


personFuzzer__Gadget_Adapter_Fuzz__fuzzer_0 =
    Gadget.Adapter.Fuzz.fuzzer personGadget__Gadget_Adapter_Fuzz__fuzzer_0


fuzzedPerson__Gadget_Adapter_Fuzz__fuzzer_0 =
    Fuzz.examples 1 personFuzzer__Gadget_Adapter_Fuzz__fuzzer_0


type alias Person__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    Gadget.record Person__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0
        |> Gadget.field
            .name
            nameGadget__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0
        |> Gadget.field .age Gadget.int
        |> Gadget.endRecord


nameGadget__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    Gadget.string |> Gadget.label "name"


personFuzzer__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    Gadget.Adapter.Fuzz.fuzzerWithOverrides
        [ Gadget.Adapter.Fuzz.override "name" Gadget.string (Fuzz.constant "Ed")
        ]
        personGadget__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0


fuzzedPerson__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    Fuzz.examples 1 personFuzzer__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0


gadget__Gadget_Adapter_Html__view_0 =
    Gadget.int


view__Gadget_Adapter_Html__view_0 =
    Gadget.Adapter.Html.view gadget__Gadget_Adapter_Html__view_0 1


gadget__Gadget_Adapter_Json__decoder_0 =
    Gadget.int


jsonString__Gadget_Adapter_Json__decoder_0 =
    "{\"int\":1}"


decoder__Gadget_Adapter_Json__decoder_0 =
    Gadget.Adapter.Json.decoder gadget__Gadget_Adapter_Json__decoder_0


result__Gadget_Adapter_Json__decoder_0 =
    Json.Decode.decodeString
        decoder__Gadget_Adapter_Json__decoder_0
        jsonString__Gadget_Adapter_Json__decoder_0


gadget__Gadget_Adapter_Json__encode_0 =
    Gadget.int


json__Gadget_Adapter_Json__encode_0 =
    Gadget.Adapter.Json.encode gadget__Gadget_Adapter_Json__encode_0 1


jsonString__Gadget_Adapter_Json__encode_0 =
    Json.Encode.encode 0 json__Gadget_Adapter_Json__encode_0


type alias Person__Gadget_Adapter_Random__generator_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget_Adapter_Random__generator_0 =
    Gadget.record Person__Gadget_Adapter_Random__generator_0
        |> Gadget.field .name Gadget.string
        |> Gadget.field .age Gadget.int
        |> Gadget.endRecord


personGenerator__Gadget_Adapter_Random__generator_0 =
    Gadget.Adapter.Random.generator
        personGadget__Gadget_Adapter_Random__generator_0


randomPerson__Gadget_Adapter_Random__generator_0 =
    Random.step
        personGenerator__Gadget_Adapter_Random__generator_0
        (Random.initialSeed 2)
        |> Tuple.first


type alias Person__Gadget_Adapter_Random__generatorWithOverrides_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget_Adapter_Random__generatorWithOverrides_0 =
    Gadget.record Person__Gadget_Adapter_Random__generatorWithOverrides_0
        |> Gadget.field
            .name
            nameGadget__Gadget_Adapter_Random__generatorWithOverrides_0
        |> Gadget.field .age Gadget.int
        |> Gadget.endRecord


nameGadget__Gadget_Adapter_Random__generatorWithOverrides_0 =
    Gadget.string |> Gadget.label "name"


personGenerator__Gadget_Adapter_Random__generatorWithOverrides_0 =
    Gadget.Adapter.Random.generatorWithOverrides
        [ Gadget.Adapter.Random.override
            "name"
            Gadget.string
            (Random.constant "Ed")
        ]
        personGadget__Gadget_Adapter_Random__generatorWithOverrides_0


randomPerson__Gadget_Adapter_Random__generatorWithOverrides_0 =
    Random.step
        personGenerator__Gadget_Adapter_Random__generatorWithOverrides_0
        (Random.initialSeed 2)
        |> Tuple.first


parser__Gadget_Adapter_String__parser_0 =
    Gadget.Adapter.String.parser (Gadget.list Gadget.int)


parsed__Gadget_Adapter_String__parser_0 =
    Parser.run parser__Gadget_Adapter_String__parser_0 "l[i(1),i(2),i(3)]"


printer__Gadget_Adapter_String__print_0 =
    Gadget.Adapter.String.print (Gadget.list Gadget.int)


printed__Gadget_Adapter_String__print_0 =
    printer__Gadget_Adapter_String__print_0 [ 1, 2, 3 ]
