module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
-}

import Array
import Dict
import Expect
import Fuzz
import Gadget
import Gadget.Adapter.Diff
import Gadget.Adapter.Fuzz
import Gadget.Adapter.Json
import Json.Decode
import Set
import Test


tests : Test.Test
tests =
    Test.describe
        "documentation code snippets"
        [ Test.describe
            "readme"
            [ Test.describe
                "code snippet 0"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Json.Decode.Value
                            unused =
                                json__Readme_0
                        in
                        Expect.pass
                    )
                , Test.test
                    "1"
                    (\() ->
                        decoded__Readme_0
                            |> Expect.equal (Result.Ok input__Readme_0)
                    )
                , Test.test
                    "2"
                    (\() ->
                        fuzzed__Readme_0
                            |> Expect.equal [ { age = 92, name = "o \n\\" } ]
                    )
                ]
            ]
        , Test.describe
            "Gadget"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget Person__Gadget__Header_0
                                unused =
                                    personGadget__Gadget__Header_0
                            in
                            Expect.pass
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget Shape__Gadget__Header_1
                                unused =
                                    shapeGadget__Gadget__Header_1
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "array"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Array.Array Basics.Int)
                                unused =
                                    arrayGadget__Gadget__array_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "dict"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Dict.Dict Basics.Int String.String)
                                unused =
                                    dictGadget__Gadget__dict_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "label"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget Basics.Int
                                unused =
                                    labelled__Gadget__label_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "list"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (List Basics.Int)
                                unused =
                                    listGadget__Gadget__list_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "map"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (List Char.Char)
                                unused =
                                    charListGadget__Gadget__map_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "maybe"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Maybe.Maybe Basics.Int)
                                unused =
                                    maybeGadget__Gadget__maybe_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "result"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Result.Result String.String Basics.Int)
                                unused =
                                    resultGadget__Gadget__result_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "set"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Set.Set Basics.Int)
                                unused =
                                    dictGadget__Gadget__set_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "triple"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget ( String.String, Basics.Int, Basics.Float )
                                unused =
                                    tripleGadget__Gadget__triple_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "tuple"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget ( String.String, Basics.Int )
                                unused =
                                    tupleGadget__Gadget__tuple_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Diff"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Adapter.Diff.Changes
                                unused =
                                    changes__Gadget_Adapter_Diff__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Gadget.Adapter.Diff.patch
                                gadget__Gadget_Adapter_Diff__Header_0
                                changes__Gadget_Adapter_Diff__Header_0
                                oldValue__Gadget_Adapter_Diff__Header_0
                                |> Expect.equal (Result.Ok [ 1, 2, 3, 4 ])
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Fuzz"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Fuzz.Fuzzer Basics.Int
                                unused =
                                    fuzzer__Gadget_Adapter_Fuzz__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Fuzz.examples
                                1
                                fuzzer__Gadget_Adapter_Fuzz__Header_0
                                |> Expect.equal [ 105 ]
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            Fuzz.examples
                                1
                                fuzzer__Gadget_Adapter_Fuzz__Header_1
                                |> Expect.equal [ 3 ]
                        )
                    ]
                ]
            ]
        ]


type alias User__Readme_0 =
    { name : String.String, age : Basics.Int }


input__Readme_0 =
    { name = "Ed", age = 44 }


gadget__Readme_0 : Gadget.Gadget User__Readme_0
gadget__Readme_0 =
    Gadget.record User__Readme_0
        |> Gadget.field .name Gadget.string
        |> Gadget.field .age Gadget.int
        |> Gadget.endRecord


json__Readme_0 =
    Gadget.Adapter.Json.encode gadget__Readme_0 input__Readme_0


decoded__Readme_0 =
    Json.Decode.decodeValue
        (Gadget.Adapter.Json.decoder gadget__Readme_0)
        json__Readme_0


fuzzed__Readme_0 =
    Fuzz.examples 1 (Gadget.Adapter.Fuzz.fuzzer gadget__Readme_0)


type alias Person__Gadget__Header_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget__Header_0 =
    Gadget.record Person__Gadget__Header_0
        |> Gadget.field .name Gadget.string
        |> Gadget.field .age Gadget.int
        |> Gadget.endRecord


type Shape__Gadget__Header_1
    = Rectangle__Gadget__Header_1 Basics.Int Basics.Int
    | Circle__Gadget__Header_1 Basics.Int


shapeGadget__Gadget__Header_1 =
    Gadget.custom
        (\rectangle circle variant ->
            case variant of
                Rectangle__Gadget__Header_1 width height ->
                    rectangle width height

                Circle__Gadget__Header_1 radius ->
                    circle radius
        )
        |> Gadget.variant2 Rectangle__Gadget__Header_1 Gadget.int Gadget.int
        |> Gadget.variant1 Circle__Gadget__Header_1 Gadget.int
        |> Gadget.endCustom


arrayGadget__Gadget__array_0 =
    Gadget.array Gadget.int


dictGadget__Gadget__dict_0 =
    Gadget.dict Gadget.int Gadget.string


labelled__Gadget__label_0 =
    Gadget.int |> Gadget.label "age"


listGadget__Gadget__list_0 =
    Gadget.list Gadget.int


charListGadget__Gadget__map_0 =
    Gadget.string |> Gadget.map String.toList String.fromList


maybeGadget__Gadget__maybe_0 =
    Gadget.maybe Gadget.int


resultGadget__Gadget__result_0 =
    Gadget.result Gadget.string Gadget.int


dictGadget__Gadget__set_0 =
    Gadget.set Gadget.int


tripleGadget__Gadget__triple_0 =
    Gadget.triple Gadget.string Gadget.int Gadget.float


tupleGadget__Gadget__tuple_0 =
    Gadget.tuple Gadget.string Gadget.int


gadget__Gadget_Adapter_Diff__Header_0 =
    Gadget.list Gadget.int


oldValue__Gadget_Adapter_Diff__Header_0 =
    [ 1, 2, 3 ]


newValue__Gadget_Adapter_Diff__Header_0 =
    [ 1, 2, 3, 4 ]


changes__Gadget_Adapter_Diff__Header_0 =
    Gadget.Adapter.Diff.diff
        gadget__Gadget_Adapter_Diff__Header_0
        oldValue__Gadget_Adapter_Diff__Header_0
        newValue__Gadget_Adapter_Diff__Header_0


gadget__Gadget_Adapter_Fuzz__Header_0 =
    Gadget.int


fuzzer__Gadget_Adapter_Fuzz__Header_0 =
    Gadget.Adapter.Fuzz.fuzzer gadget__Gadget_Adapter_Fuzz__Header_0


gadget__Gadget_Adapter_Fuzz__Header_1 =
    Gadget.int |> Gadget.label "override-me"


fuzzer__Gadget_Adapter_Fuzz__Header_1 =
    Gadget.Adapter.Fuzz.fuzzerWithOverrides
        [ Gadget.Adapter.Fuzz.override
            "override-me"
            Gadget.int
            (Fuzz.constant 3)
        ]
        gadget__Gadget_Adapter_Fuzz__Header_1
