module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
-}

import Expect
import Fuzz
import Gadget
import Gadget.Adapter.Diff
import Gadget.Adapter.Fuzz
import Gadget.Adapter.Json
import Json.Decode
import Test


tests : Test.Test
tests =
    Test.describe
        "documentation code snippets"
        [ Test.describe
            "readme"
            [ Test.describe
                "code snippet 0"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Json.Decode.Value
                            unused =
                                json__Readme_0
                        in
                        Expect.pass
                    )
                , Test.test
                    "1"
                    (\() ->
                        decoded__Readme_0
                            |> Expect.equal (Result.Ok input__Readme_0)
                    )
                , Test.test
                    "2"
                    (\() ->
                        fuzzed__Readme_0
                            |> Expect.equal [ { age = 92, name = "o \n\\" } ]
                    )
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Diff"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Adapter.Diff.Changes
                                unused =
                                    changes__Gadget_Adapter_Diff__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Gadget.Adapter.Diff.patch
                                gadget__Gadget_Adapter_Diff__Header_0
                                changes__Gadget_Adapter_Diff__Header_0
                                oldValue__Gadget_Adapter_Diff__Header_0
                                |> Expect.equal (Result.Ok [ 1, 2, 3, 4 ])
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Fuzz"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Fuzz.Fuzzer Basics.Int
                                unused =
                                    fuzzer__Gadget_Adapter_Fuzz__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Fuzz.examples
                                1
                                fuzzer__Gadget_Adapter_Fuzz__Header_0
                                |> Expect.equal [ 105 ]
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            Fuzz.examples
                                1
                                fuzzer__Gadget_Adapter_Fuzz__Header_1
                                |> Expect.equal [ 3 ]
                        )
                    ]
                ]
            ]
        ]


type alias User__Readme_0 =
    { name : String.String, age : Basics.Int }


input__Readme_0 =
    { name = "Ed", age = 44 }


gadget__Readme_0 : Gadget.Gadget User__Readme_0
gadget__Readme_0 =
    Gadget.record User__Readme_0
        |> Gadget.field .name Gadget.string
        |> Gadget.field .age Gadget.int
        |> Gadget.endRecord


json__Readme_0 =
    Gadget.Adapter.Json.encode gadget__Readme_0 input__Readme_0


decoded__Readme_0 =
    Json.Decode.decodeValue
        (Gadget.Adapter.Json.decoder gadget__Readme_0)
        json__Readme_0


fuzzed__Readme_0 =
    Fuzz.examples 1 (Gadget.Adapter.Fuzz.fuzzer gadget__Readme_0)


gadget__Gadget_Adapter_Diff__Header_0 =
    Gadget.list Gadget.int


oldValue__Gadget_Adapter_Diff__Header_0 =
    [ 1, 2, 3 ]


newValue__Gadget_Adapter_Diff__Header_0 =
    [ 1, 2, 3, 4 ]


changes__Gadget_Adapter_Diff__Header_0 =
    Gadget.Adapter.Diff.diff
        gadget__Gadget_Adapter_Diff__Header_0
        oldValue__Gadget_Adapter_Diff__Header_0
        newValue__Gadget_Adapter_Diff__Header_0


gadget__Gadget_Adapter_Fuzz__Header_0 =
    Gadget.int


fuzzer__Gadget_Adapter_Fuzz__Header_0 =
    Gadget.Adapter.Fuzz.fuzzer gadget__Gadget_Adapter_Fuzz__Header_0


gadget__Gadget_Adapter_Fuzz__Header_1 =
    Gadget.int |> Gadget.label "override-me"


fuzzer__Gadget_Adapter_Fuzz__Header_1 =
    Gadget.Adapter.Fuzz.fuzzerWithOverrides
        [ Gadget.Adapter.Fuzz.override
            "override-me"
            Gadget.int
            (Fuzz.constant 3)
        ]
        gadget__Gadget_Adapter_Fuzz__Header_1
